'use client'

import {
  createClient,
  hasSupabaseConfig,
} from '@/lib/supabase/client'
import { shouldUseServiceWorker } from '@/lib/dev-flags'

const VAPID_PUBLIC_KEY = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY
const SERVICE_WORKER_READY_TIMEOUT_MS = 7000

function hasVapidPublicKey() {
  return Boolean(VAPID_PUBLIC_KEY)
}

function getUserTimezone() {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
  } catch {
    return 'UTC'
  }
}

function urlBase64ToUint8Array(value: string) {
  const padding = '='.repeat((4 - (value.length % 4)) % 4)
  const base64 = `${value}${padding}`.replace(/-/g, '+').replace(/_/g, '/')
  const rawData = window.atob(base64)
  const output = new Uint8Array(rawData.length)

  for (let index = 0; index < rawData.length; index += 1) {
    output[index] = rawData.charCodeAt(index)
  }

  return output
}

function getVapidApplicationServerKey(value: string) {
  const key = urlBase64ToUint8Array(value.trim())

  if (key.byteLength !== 65 || key[0] !== 4) {
    throw new Error(
      'The deployed VAPID public key is invalid. Use the publicKey value generated by web-push.',
    )
  }

  return key
}

function canUsePushManager() {
  return (
    shouldUseServiceWorker() &&
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window
  )
}

async function withTimeout<T>(
  promise: Promise<T>,
  timeoutMs: number,
  message: string,
) {
  let timeoutId: number | undefined

  try {
    return await Promise.race([
      promise,
      new Promise<never>((_, reject) => {
        timeoutId = window.setTimeout(() => reject(new Error(message)), timeoutMs)
      }),
    ])
  } finally {
    if (timeoutId) {
      window.clearTimeout(timeoutId)
    }
  }
}

async function getReadyServiceWorkerRegistration() {
  if (!canUsePushManager()) {
    throw new Error('Push notifications are not supported in this browser.')
  }

  return withTimeout(
    navigator.serviceWorker.ready,
    SERVICE_WORKER_READY_TIMEOUT_MS,
    'The service worker is not ready for push notifications yet.',
  )
}

function toPushSubscriptionRow(userId: string, subscription: PushSubscription) {
  const serialized = subscription.toJSON()
  const endpoint = serialized.endpoint
  const auth = serialized.keys?.auth
  const p256dh = serialized.keys?.p256dh

  if (!endpoint || !auth || !p256dh) {
    throw new Error('The browser did not return a complete push subscription.')
  }

  return {
    auth,
    endpoint,
    p256dh,
    revoked_at: null,
    timezone: getUserTimezone(),
    user_agent: navigator.userAgent,
    user_id: userId,
  }
}

async function upsertRemotePushSubscription(
  userId: string,
  subscription: PushSubscription,
) {
  const supabase = createClient()
  const row = toPushSubscriptionRow(userId, subscription)
  const { error } = await supabase.rpc('upsert_push_subscription', {
    p_auth: row.auth,
    p_endpoint: row.endpoint,
    p_p256dh: row.p256dh,
    p_timezone: row.timezone,
    p_user_agent: row.user_agent,
  })

  if (error) {
    throw error
  }
}

export function getPushReminderErrorMessage(error: unknown) {
  const message =
    error instanceof Error
      ? error.message
      : typeof error === 'object' && error && 'message' in error
        ? String(error.message)
        : String(error)
  const lowerMessage = message.toLowerCase()

  if (lowerMessage.includes('upsert_push_subscription')) {
    return 'Reminder database setup is missing. Re-run supabase/schema.sql, then redeploy.'
  }

  if (
    lowerMessage.includes('push_subscriptions') ||
    lowerMessage.includes('schema cache') ||
    lowerMessage.includes('relation') ||
    lowerMessage.includes('table')
  ) {
    return 'Reminder database tables are missing. Re-run supabase/schema.sql in Supabase.'
  }

  if (
    lowerMessage.includes('applicationserverkey') ||
    lowerMessage.includes('vapid') ||
    lowerMessage.includes('invalid character') ||
    lowerMessage.includes('public key')
  ) {
    return 'The deployed VAPID public key is missing or invalid. Check NEXT_PUBLIC_VAPID_PUBLIC_KEY.'
  }

  if (
    lowerMessage.includes('push service error') ||
    lowerMessage.includes('registration failed')
  ) {
    return 'The browser push service rejected registration. Check that the deployed NEXT_PUBLIC_VAPID_PUBLIC_KEY is the generated public key, then try another browser/network if it still fails.'
  }

  if (
    lowerMessage.includes('service worker') ||
    lowerMessage.includes('not supported')
  ) {
    return 'Push is not ready in this browser yet. Refresh after the app finishes installing, then try again.'
  }

  if (
    lowerMessage.includes('row-level security') ||
    lowerMessage.includes('permission denied') ||
    lowerMessage.includes('unauthorized')
  ) {
    return 'Supabase rejected the subscription save. Make sure you are signed in and the latest schema policies are applied.'
  }

  return message || 'Could not save reminder settings. Please try again.'
}

async function revokeRemotePushSubscription(
  endpoint: string,
  userId?: string,
) {
  if (!hasSupabaseConfig()) {
    return
  }

  const supabase = createClient()
  let query = supabase
    .from('push_subscriptions')
    .update({
      revoked_at: new Date().toISOString(),
    })
    .eq('endpoint', endpoint)

  if (userId) {
    query = query.eq('user_id', userId)
  }

  await query
}

export function canUseSupabasePushReminders() {
  return hasSupabaseConfig() && hasVapidPublicKey() && canUsePushManager()
}

export async function enableRemotePaymentReminders(userId: string) {
  if (!canUseSupabasePushReminders() || !VAPID_PUBLIC_KEY) {
    throw new Error('Supabase push reminders are not configured.')
  }

  const registration = await getReadyServiceWorkerRegistration()
  const existingSubscription = await registration.pushManager.getSubscription()

  if (existingSubscription) {
    await revokeRemotePushSubscription(existingSubscription.endpoint, userId).catch(
      () => undefined,
    )
    await existingSubscription.unsubscribe()
  }

  const subscription = await registration.pushManager.subscribe({
    applicationServerKey: getVapidApplicationServerKey(VAPID_PUBLIC_KEY),
    userVisibleOnly: true,
  })

  await upsertRemotePushSubscription(userId, subscription)

  return subscription
}

export async function disableRemotePaymentReminders(userId?: string) {
  if (!canUsePushManager()) {
    return
  }

  const registration = await navigator.serviceWorker.ready.catch(() => null)
  const subscription = await registration?.pushManager
    .getSubscription()
    .catch(() => null)

  if (!subscription) {
    return
  }

  await revokeRemotePushSubscription(subscription.endpoint, userId).catch(
    () => undefined,
  )
  await subscription.unsubscribe().catch(() => undefined)
}
